name: Bug Report
description: for reporting unintended features or errors in the program
title: "[Bug]: "
labels: ["bug", ]
assignees:
  - Jln2002

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us make the Captain Jack Public server a better experince by reporting this issue
  - type: input
    id: contact
    attributes:
      label: Discord ID
      description: Please tell us your discord ID incase we need more info
      placeholder: Discord ID 
    validations:
      required: True
      
  body:
  - type: textarea
    id: what-happened
    attributes:
      label: 
      description: Please Decribe the Issue that occured in Detail if possible
      placeholder: please describe what happened
      value: "A bug happened!"
    validations:
      required: true
      

  - type: dropdown
    id: version
    attributes:
      label: Mods
      description: Please if viable select the mod that caused the issue from the list below
      options:
        - Elevator Mod
        - SOBT Weapon Pack 2
        - Weapon Core (default)
        - Not Mod related
    validations:
      required: true
      
  

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Jln2002/CW_SE_Releases/blob/master/infofiles/Code-of-conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
