name: Captain Jack Public Server Feeback System
description: thank you for taking time to give us feedback for the Captain Jack Public Server
assignees:
  - Nexi,Orion,Mors
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us make the Captain Jack Public Server a better experince for you and others
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Please enter your discord ID incase we need to contact you for more info
      placeholder: Discord ID
    validations:
      required: true
  - type: textarea
    id: what-did-you-like
    attributes:
      label: what did you like
      description: what did you enjoy with event!
      placeholder: :)
      value: "A bug happened!"
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Issue Mod
      description: how many stars would you give this event
      options:
        - 1 
        - 2 
        - 3
        - 4
        - 5
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Jln2002/CW_SE_Releases/blob/master/infofiles/Code-of-conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
